### ISSUE TITLE
List command not showing in Discord

### ISSUE THREAD

**Issue by BrianLanghoor** [Assaro/DD_Bot#29]
Not sure if it has been removed. But by looking at the code it should still be there. In my case, there is no /list command showing up in Discord

![image](https://github.com/Assaro/DD_Bot/assets/15155172/52c91c47-a07d-4ca2-ab2d-d85c6c5b0fd5)

Also when just typing /list nothing happens. 

I can live without it, but thought you might wanted to be informed by this.

**Comment by Assaro** [comment]
This is a problem that occurs for an unknown reason. My best guess is that it is a rate limit by Discord's API combined with a caching problem. I have had it occur much more severely and managed to mitigate it mostly by chainging the command initialization. I may have to do more research, but it is a little hit or miss for me because i cannot reproduce the issue. If you want to take up the hassle try creating a second bot and see if that fixes it.
